### ISSUE TITLE
Company Search Returning Inconsistent Results

### ISSUE THREAD

**Issue by Stephman1** [Stephman1/fraudulent-business-address#14]
* The company search functionality returns unexpected results when searching for 4 Menelik Road and 9 Menelik Road
* The correct result is returned for "4 Menelik Road", i.e., the business registered at that address is returned
* An incorrect result is returned for "9 Menelik Road", i.e., 6 businesses from the same street but not registered at that exact address are returned

![4-menelik](https://github.com/user-attachments/assets/93cff313-459d-4651-8747-2f389abeb5ea)

![9-menelik](https://github.com/user-attachments/assets/7b445a65-21b5-4b0f-a2d0-3bc3be0be19d)

**Comment by makson2006** [comment]
Hi, can I get code for this project?

**Comment by Stephman1** [comment]
Sure! Did you want to fork the repo? I think that would be the best option if you wanted to work on this issue
